### ISSUE TITLE
持续更新的前端诶嘿

### ISSUE THREAD

**Issue by Ganother** [Ganother/-#1]
# 移动端
* **三星note呼出键盘，会取消掉最上面的margin，解决方案是改成padding**
* **IOS safari，页面进行滑动时，浏览器会把页面上的渲染进行锁定。**
* **移动端1px border：**
不支持after清浮动的方法，不支持有overflow的元素。
``` css
%top_border{

position: relative;

&:after{

content: "";

position: absolute;

top: 0;

left: 0;

right: 0;

height: 0;

border-bottom: 1px solid #ddd;

-webkit-transform: scaleY(0.5);

-webkit-transform-origin: 0 0;

}

}



%bottom_border{

position: relative;

&:after{

content: "";

position: absolute;

bottom: -1px;  // transform 不改变元素占位

left: 0;

right: 0;

height: 0;

border-bottom: 1px solid #ddd;

-webkit-transform: scaleY(0.5);

-webkit-transform-origin: 0 0;

}

}
```
* **部分移动端老浏览器不支持rotate3d(1,1,1,360deg), 改为分开写X，Y，Z**
* **部分移动端老浏览器伪元素动画失效，改为放一个真实元素**
* **transform并不改变元素占位，布局注意。**
* **IOS Safari 粘贴不触发keyup事件，改为input**
* **window.scrollTo(x,y)**部分机型不兼容
* **浏览器返回后，一般会重新执行js，然而ios不会，如果需要重新执行js，添加代码：**
``` javascript
        if (/(iPhone|iPad|iPod)/i.test(navigator.userAgent)) {
            window.onpageshow = function (event) {
                if (event.persisted) { //假如页面是从缓存中得到
                    window.location.reload() //直接刷新，或者重新调用需要调用的js
                }
            }
        };
``` 
* **微信中 输入框focus时会自动scroll，使focus事件里的scroll无效（有待进一步验证）。**
* **有一些机型 （华为 mate n）输入框focus时不会自动滚动使输入框出现在视野里，一定要添加scroll的行为。**
